[workspace]

members = [
    # dune2 data lib
    "packages/dune2",
    # dune2 data command line tools
    "packages/rctoolkit",
    "packages/unpak",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
