[package]
name = "dune2-assets-toolkit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
bitvec = "1.0.1"
clap = { version = "4.2.7", features = ["derive", "env"] }
dune2-assets = { path = "../dune2" }
image = "0.25.2"
paste = "1.0.15"
serde = "1.0.162"
toml = "0.8.19"
