[package]
name = "dune2-rc-toolkit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive", "env"] }
dune2-resources = { path = "../dune2", features = ["shp", "icn"] }
image = "0.24.6"
serde = "1.0.162"
toml = "0.7.3"
