[package]
name = "dune2-rc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
shp = ["dep:bitvec"]
icn = []
map = []
wasm = ["dep:js-sys", "dep:wasm-bindgen", "dep:web-sys"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
bitvec = { version = "1.0.1", optional = true }
flate2 = { version = "1.0.26", default-features = false, features = ["rust_backend"] }
js-sys = { version = "0.3.70", optional = true }
paste = "1.0.12"
rmp-serde = "1.1.1"
serde = { version = "1.0.209", features = ["derive"] }
wasm-bindgen = { version = "0.2.93", optional = true }
web-sys = { version = "0.3.70", features = ["console", "ImageData"], optional = true }
