[package]
name = "dune2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
shp = ["dep:bitvec"]
icn = []
map = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = { version = "1.0.1", optional = true }
flate2 = { version = "1.0.26", default-features = false, features = ["rust_backend"] }
paste = "1.0.12"
rmp-serde = "1.1.1"
serde = { version = "1.0.162", features = ["derive"] }
