[package]
name = "pal2bmp"
version = "0.1.0"
edition = "2021"
authors = ["NealRame <https://github.com/NealRame>"]
description = "Converts PAL files to BMP files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dune2 = { path = "../dune2" }
clap = { version = "4.1.8", features = ["derive", "env"] }
